# based on https://github.com/psf/black/blob/main/.github/workflows/lint.yml
name: Lint

on:
  push:
    branches: [main, feat/gh-actions]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install tox

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: Run tox
        run: tox
